### ISSUE TITLE
a-camera 대신 Camera를 써보면 어떨까요?

### ISSUE THREAD

**Issue by juunini** [maemenaver/rain-react-three#1]
rotation값이나 다른 값들도 Camera 태그에 직접 넣을 수 있어요.
힘들게 a-camera를 찾아서 하실 필요는 없답니다.

디펜던시에 떳길래 궁금해서 한번 봤어요 ㅎㅎ
도움이 필요하시면 언제든 연락주세요.

**Comment by omizha** [comment]
@juunini 🤭 세상에, 평소에 velog 게시물 잘 보고 있습니다!
누추한 토이 레포지토리에 찾아오셔서 정말 영광스러워요!! ✨

레포지토리를 꾸미지 않아서 뭐하는 곳인가.. 싶으시겠지만
https://redstapler.co/three-js-realistic-rain-tutorial/
이것을 그대로 a-frame 환경으로 옮겨보는 시도를 하고 있었습니다!

우선 Camera 대신에 a-camera를 썼던 이유가,
three.js의 카메라에 대한 개념이 부족해서 rotation을 제가 원하는대로 작동하지 않아
처음에는 Camera로 시도해봤다가 a-camera로도 시도를 해본 흔적이었습니다 😵
rotation을 [1.16, -0.12, 0.27]으로 세팅을 했는데, 실제로 실행하고 디버그값을 까보면 엉뚱한 값이 나와버리더라고요..
지금으로써는 카메라가 아니라 Control을 건드려야 하나? 추측을 하고 있습니다.
-> 카메라 혹은 컨트롤의 개념이 부족한 부분은 threejs-journey 강의를 결제해서 깊게 공부해보는 것으로 해결할 예정입니다!

다만 도움이 필요한 부분이 있다면,
Aframe 라이브러리에서는 png파일의 transparent가 제대로 작동하지 않는 이슈가 있더라고요.
threejs에서는 잘 작동을 하는지라 Aframe을 포기해야 하나..? 하는 문제에 직면하고 있습니다.
본 레포지토리에 사용한 smoke.png는 알파채널과 RGB채널이 끝부분에 섞여있어서
alphaTest를 사용하는 방식으로 문제를 해결하려 하면 끝에 예쁘게 안짤리더라고요.. 😢
(https://github.com/maemenaver/rain-react-three/blob/master/public/smoke.png)

이러한 부분은 어떤 환경(배경)의 구름을 구현하는 방식으로 활용하고 있는데
여유가 혹시 되신다면, 쥬니니님께서는 이에 대해 혹시 어떤 솔루션을 사용하시는지 여쭙고자 합니다..!!
(관련 레포지토리 : https://github.com/maemenaver/yoasobi-loveletter)

**Comment by juunini** [comment]
rotation 값을 적용시키려면 `lookControls={{ enabled: false }}` 설정을 해야해요.
고개를 움직일 수 있게 설정하면 카메라의 rotation이 적용되지 않더라구요.

고개도 움직일 수 있으면서 rotation을 시키려면 카메라 외의 모든 object를 rotation 시켜야 하죠 ㄷㄷ

**Comment by omizha** [comment]
@juunini Aframe의 기본적으로 활성화된 lookControls가 문제였네요..!! 감사합니다! ☺☺🙏🙏👍👍✨✨

**Comment by maemenaver** [comment]
png파일의 transparent가 제대로 작동하지 않는 이슈에 대해서는
alphaTest 이외에도 depthTest 및 depthWrite를 이용해서 문제를 해결했습니다.

**Comment by omizha** [comment]
> 다만 도움이 필요한 부분이 있다면, Aframe 라이브러리에서는 png파일의 transparent가 제대로 작동하지 않는 이슈가 있더라고요. threejs에서는 잘 작동을 하는지라 Aframe을 포기해야 하나..? 하는 문제에 직면하고 있습니다. 본 레포지토리에 사용한 smoke.png는 알파채널과 RGB채널이 끝부분에 섞여있어서 alphaTest를 사용하는 방식으로 문제를 해결하려 하면 끝에 예쁘게 안짤리더라고요.. 😢 (https://github.com/maemenaver/rain-react-three/blob/master/public/smoke.png)
> 
> 이러한 부분은 어떤 환경(배경)의 구름을 구현하는 방식으로 활용하고 있는데 여유가 혹시 되신다면, 쥬니니님께서는 이에 대해 혹시 어떤 솔루션을 사용하시는지 여쭙고자 합니다..!! (관련 레포지토리 : https://github.com/maemenaver/yoasobi-loveletter)

png파일의 transparent가 제대로 작동하지 않는 이슈에 대해서는
alphaTest 이외에도 depthTest 및 depthWrite를 이용해서 문제를 해결했습니다.
